### ISSUE TITLE
old bf voice sample?

### ISSUE THREAD

**Issue by PikrlRealForReal** [MoldyGH/VsDave#11]
ik this is a stupid place to put it since its not really a issue but i just started using github (just started like not just downloading source code :|) so is there a REAL not remade offical ver of the old bf voice sample like in the old ver of house?
(please tell me if theres a better place to put this)

**Comment by FuseIsHere813** [comment]
https://gamebanana.com/tools/7698

old bf voice soundfont

**Comment by PikrlRealForReal** [comment]
> https://gamebanana.com/tools/7698
> 
> old bf voice soundfont

is as looking for another one cause im not sure if its real or not but it’ll do
