### ISSUE TITLE
Bug Report: Segfault when starting game

### ISSUE THREAD

**Issue by Kiffolisk** [MoldyGH/VsDave#13]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.
Linux (Linux Mint)

## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
Compile on Linux and play.

## Please describe your issue. Provide extensive detail and images if possible.
Segfault after the game starts. Don't know if this is a Linux issue or whatever.

**Comment by MoldyGH** [comment]
Its because of the openfl shaders used in polygonized and glitch, if you want to manually remove them then recompile you can try but that issue is out of my reach
