### ISSUE TITLE
Problem Compiling (Windows)

### ISSUE THREAD

**Issue by SomeKindofGamer** [MoldyGH/VsDave#20]
I keep getting
source/PlayState.hx:292: characters 12-24 : Type not found : VideoHandler
source/LoadingState.hx:18: lines 18-226 : ... Defined in this class
source/StoryMenuState.hx:260: characters 17-29 : Type not found : VideoHandler
source/Note.hx:339: characters 18-28 : Class<PlayState> has no field scrollType
when i try to compile
help

**Comment by MemeHoovy** [comment]
```haxelib git hxCodec https://github.com/polybiusproxy/hxCodec```

**Comment by MemeHoovy** [comment]
> Tried that, still have the same issue.

🤷🏻‍♂️it worked for me

**Comment by Erizur** [comment]
i was the one who implemented it, if youre having issues with hxcodec because you installed the haxelib instead of the git version try removing it and reinstalling it
haxelib remove hxCodec
haxelib git hxCodec https://github.com/polybiusproxy/hxCodec

**Comment by Erizur** [comment]
due to this being a common error that is already fixed for everyone who wants to try compiling, im closing this.

**Comment by MrMichaDaDude** [comment]
> haxelib remove hxCodec

and when i go with just the github version it just says its missing

**Comment by MrMichaDaDude** [comment]
> 

nvm

**Comment by luacoder279** [comment]
for some reason the git wont work since i have git on my pc
