### ISSUE TITLE
i cant compile

### ISSUE THREAD

**Issue by JP1619** [MoldyGH/VsDave#21]
source/PlayState.hx:6180: characters 11-20 : Warning : this pattern is unused
source/PlayState.hx:6180: characters 11-20 : Warning : this pattern is unused
source/CharacterSelectState.hx:147: characters 3-39 : Warning : 'FlxCamera.defaultCameras' is deprecated, use 'FlxG.cameras.setDefaultDrawTarget' instead.
and some of the above but its just normal errors that happen not only in this one

Warning: could not find visual studio 2017 VsDevCmd
Missing: HXCPP_VARS
Error: could not automatically setup MSVC

i have the 10.0.17763.0 sdk, msvc v142 (the correct one) and community 2019
i looked at the docs from kade engine and the normal one but i couldn't find anything that would help
also sorry if its not from the source code and its me that forgot to install something

**Comment by MemeHoovy** [comment]
are you gonna explain why you can't compile? or are you just gonna leave us hanging you dumbass?

**Comment by JP1619** [comment]
> are you gonna explain why you can't compile? or are you just gonna leave us hanging you dumbass?

i forgot to type im editing it

**Comment by MemeHoovy** [comment]
you should've typed it beforehand

**Comment by JP1619** [comment]
> well, you should've typed it beforehand

alr finished it

**Comment by MemeHoovy** [comment]
did you even read the full instructions? https://github.com/ninjamuffin99/Funkin/blob/master/README.md
and for the hxcodec thing `haxelib git hxCodec https://github.com/polybiusproxy/hxCodec`

**Comment by JP1619** [comment]
> did you even read the full instructions? https://github.com/ninjamuffin99/Funkin/blob/master/README.md and for the hxcodec thing `haxelib git hxCodec https://github.com/polybiusproxy/hxCodec`

i just said i readed both kade and the one you just sended

**Comment by MemeHoovy** [comment]
you need to install MSVC v142 - VS 2019 C++ x64/x86 build tools **latest**

**Comment by JP1619** [comment]
> you need to install MSVC v142 - VS 2019 C++ x64/x86 build tools **latest** in visual studio installer

OH i thought it was a specific version

**Comment by MemeHoovy** [comment]
it is

**Comment by JP1619** [comment]
> it is

alright downloading it rn ill tell if it fixed it

**Comment by JP1619** [comment]
> it is

also what is the correct command to do? i keep getting confused with haxelib run lime build windows and lime test windows

**Comment by JP1619** [comment]
> it is

i still keep getting the same vsdevcmd 2017 error
(im using visual studio community 2019)

**Comment by MemeHoovy** [comment]
.......you know what, I think I know someone who can help

**Comment by JP1619** [comment]
> .......you know what, I think I know someone who can help

who?

**Comment by MemeHoovy** [comment]
why don't you ask these people on https://stackoverflow.com/ maybe they can help you

**Comment by MemeHoovy** [comment]
because I'm not bothering with this shit
