### ISSUE TITLE
Bug Report: i cant compile

### ISSUE THREAD

**Issue by MrMichaDaDude** [MoldyGH/VsDave#22]
i cant compile cuz it says this
source/PlayState.hx:292: characters 12-24 : Type not found : VideoHandler
source/LoadingState.hx:18: lines 18-226 : ... Defined in this class
source/StoryMenuState.hx:260: characters 17-29 : Type not found : VideoHandler
source/Note.hx:339: characters 18-28 : Class<PlayState> has no field scrollType
please help

**Comment by MoldyGH** [comment]
You probably don't have hxCodec installed 

haxelib git hxCodec https://github.com/PolybiusProxy/hxCodec

**Comment by MemeHoovy** [comment]
hi moldy!

**Comment by MrMichaDaDude** [comment]
> You probably don't have hxCodec installed
> 
> haxelib git hxCodec https://github.com/PolybiusProxy/hxCodec

i try installing with git and it freezes and when i try installing through haxe it says i already have it installed

**Comment by MrMichaDaDude** [comment]
> You probably don't have hxCodec installed
> 
> haxelib git hxCodec https://github.com/PolybiusProxy/hxCodec

ya i tried reinstalling, same error message

**Comment by MrMichaDaDude** [comment]
> You probably don't have hxCodec installed
> 
> haxelib git hxCodec https://github.com/PolybiusProxy/hxCodec

also your cool

**Comment by benjaminpants** [comment]
duplicate of #20
