### ISSUE TITLE
flps folder suspiciously empty...?

### ISSUE THREAD

**Issue by derpguy125** [MoldyGH/VsDave#25]
as of the current commit, theres only like four files in "/art/Source Files/FL Studio Project Files". what the heck's up with that? are you guys like, planning on readding the missing FLPs and such?

**Comment by derpguy125** [comment]
how do i add labels again im dumb

**Comment by MemeHoovy** [comment]
look at older commits

**Comment by MemeHoovy** [comment]
> how do i add labels again im dumb

you can't unless your a collaborator or repo owner

**Comment by RexExists** [comment]
moldy released the flps on his itch.io

**Comment by derpguy125** [comment]
> moldy released the flps on his itch.io

thanks!
