### ISSUE TITLE
How do I add shaders (source code, but not this repository)

### ISSUE THREAD

**Issue by Wither362** [MoldyGH/VsDave#28]
Hi, I’m currently working on my [Theoyeah Engine](https://github.com/Wither362/Theoyeah-Engine-DaveAndBambi) but with your shaders support, and I can’t add the shaders!
I need your help, I know that maybe you’re busy, but I need to finish with this the fast as I can, and I need help.

**Comment by ZackOui** [comment]
have u figured it out yet

**Comment by Wither362** [comment]
> have u figured it out yet

No

**Comment by benjaminpants** [comment]
please do not use the issue tracker for stuff like this.

**Comment by Wither362** [comment]
> please do not use the issue tracker for stuff like this.

Sorry
