### ISSUE TITLE
Bug Report: haxeflixel errors

### ISSUE THREAD

**Issue by luacoder279** [MoldyGH/VsDave#29]
when i try to compile it gives me this
source/PlayState.hx:292: characters 12-24 : Type not found : VideoHandler
source/LoadingState.hx:18: lines 18-226 : ... Defined in this class
source/StoryMenuState.hx:260: characters 17-29 : Type not found : VideoHandler
source/Note.hx:339: characters 18-28 : Class<PlayState> has no field scrollType
can someone help me

**Comment by mayo78** [comment]
https://github.com/MoldyGH/VsDave/issues/22

**Comment by 91ebagacm** [comment]
basically u forget install hxCodec
