### ISSUE TITLE
five nights bug and application problem

### ISSUE THREAD

**Issue by ivorivorhepl** [MoldyGH/VsDave#30]
for some reason, the "nofriend" character just stops moving and does not play any notes. and the application icon is just the lime logo. whats the problem?

**Comment by Erizur** [comment]
most likely a broken compilation, or badly installed libraries, reinstall haxe or the libraries, this is not our issue.

**Comment by ivorivorhepl** [comment]
i reinstalled haxe and libraries, and compiled like 10 times lmfao, still errors
