### ISSUE TITLE
Bug Report: Expected , or ]

### ISSUE THREAD

**Issue by Aleks-Cola** [MoldyGH/VsDave#34]
![image](https://user-images.githubusercontent.com/56561971/198685954-af184562-3aea-4a0a-8c24-342c7c8d5398.png)
help

**Comment by mayo78** [comment]
did you edit the code

**Comment by Aleks-Cola** [comment]
yes

**Comment by Aleks-Cola** [comment]
OK I JUST REALIZED SOMETHING, IM DUMB

**Comment by Aleks-Cola** [comment]
> did you edit the code
