### ISSUE TITLE
I can't compile

### ISSUE THREAD

**Issue by Tikoulla** [MoldyGH/VsDave#36]
when i try to compile it's just appears this
source/PlayState.hx:292: characters 12-24 : Type not found : VideoHandler
source/LoadingState.hx:18: lines 18-226 : ... Defined in this class
source/StoryMenuState.hx:260: characters 17-29 : Type not found : VideoHandler
source/Note.hx:339: characters 18-28 : Class<PlayState> has no field scrollType

**Comment by MemeHoovy** [comment]
You didn’t install hxCodec

**Comment by mayo78** [comment]
https://github.com/MoldyGH/VsDave/issues/22

**Comment by Erizur** [comment]
Install hxCodec from the github, instructions are in there.
