### ISSUE TITLE
i mean this isnt a bug but i was tryin to do smth so

### ISSUE THREAD

**Issue by AverageDaveLover65** [MoldyGH/VsDave#40]
Okay so I was tryin to use the source of this to do some wacky shit and then once I'm done with everything, this pops out of nowhere.
![image](https://user-images.githubusercontent.com/110858723/200105999-c288f728-ce2a-435a-95e0-54da0dc929e8.png)
Do you guys have any idea on how to fix this? Because I wanna finish this.

**Comment by AverageDaveLover65** [comment]
note: I was messing around with PlayState.hx and MainMenuState.hx to be exact

**Comment by BushTrain460615** [comment]
what did you change in the play state and main menu state

**Comment by Erizur** [comment]
not a bug LOL
