### ISSUE TITLE
Where's 3.0 FLA Files?

### ISSUE THREAD

**Issue by FrozenOfficialGITHUB** [MoldyGH/VsDave#42]
Can Someone Send Me FLA's Of 3.0? I Need Them.

**Comment by mayo78** [comment]
![Screenshot 2022-11-14 11 44 46 AM](https://user-images.githubusercontent.com/75394229/201717105-db2f3fd6-a9c8-461f-ac01-0707b331d038.png)

**Comment by FrozenOfficialGITHUB** [comment]
i see...

**Comment by mayo78** [comment]
close the issue

**Comment by Evertonlobao** [comment]
i have the 3.0 dave flas 
they are here: https://drive.google.com/drive/folders/1ig6vmj3zMpym173PObZWXd0TuRZ83ZGr

**Comment by Erizur** [comment]
theres a lot of ways to check out the latest flas, look in the wiki or the internet.

**Comment by FrozenOfficialGITHUB** [comment]
i found them.
