### ISSUE TITLE
Enhancement: add 3.0 stuff

### ISSUE THREAD

**Issue by Cap6ailB3an** [MoldyGH/VsDave#52]
nothing wrong just make a relese with 3.0

**Comment by MemeHoovy** [comment]
no, go play the mod on Gamebanana

**Comment by Evertonlobao** [comment]
@Cap6ailB3an they are here https://drive.google.com/drive/folders/1ig6vmj3zMpym173PObZWXd0TuRZ83ZGr?usp=sharing

**Comment by Erizur** [comment]
we're currently bugfixing some stuff, the latest 3.0 release will be added as soon as we finish.
