### ISSUE TITLE
getting this error when trying to compile a older version from the commits

### ISSUE THREAD

**Issue by alex-codes-stuff** [MoldyGH/VsDave#53]
gives me this error:
source/CharacterSelectState.hx:3: characters 1-68 : io.newgrounds.objects.events.Result has no field or subtype GetCurrentVersionResult
source/NGio.hx:12: characters 1-68 : io.newgrounds.objects.events.Result has no field or subtype GetCurrentVersionResult
source/NGio.hx:13: characters 1-61 : io.newgrounds.objects.events.Result has no field or subtype GetVersionResult
source/NGio.hx:47: characters 62-76 : io.newgrounds.Call<io.newgrounds.objects.events.GetCurrentVersionData> has no field addDataHandler (Suggestion: addStatusHandler)
source/NGio.hx:47: characters 104-127 : Type not found : GetCurrentVersionResult
source/NGio.hx:97: characters 25-39 : () -> Void should be Null<io.newgrounds.objects.events.Outcome<io.newgrounds.CallError> -> Void>
source/NGio.hx:97: characters 25-39 : ... For optional function argument 'callback'
source/NGio.hx:100: characters 30-45 : () -> Void should be Null<io.newgrounds.objects.events.Outcome<io.newgrounds.CallError> -> Void>
source/NGio.hx:100: characters 30-45 : ... For optional function argument 'callback'
source/NGio.hx:86: characters 25-34 : () -> Void should be Null<io.newgrounds.LoginOutcome -> Void>
source/NGio.hx:86: characters 25-34 : ... For optional function argument 'callback'
C:/Users/alexb/haxe/lib/polymod/git/polymod/hscript/_internal/PolymodScriptClass.hx:366: characters 69-73 : polymod.hscript._internal.ErrorEx has no field line
C:/Users/alexb/haxe/lib/polymod/git/polymod/hscript/_internal/PolymodScriptClass.hx:60: characters 52-56 : polymod.hscript._internal.ErrorEx has no field line
C:/Users/alexb/haxe/lib/polymod/git/polymod/hscript/_internal/PolymodScriptClass.hx:63: characters 87-91 : polymod.hscript._internal.ErrorEx has no field line
C:/Users/alexb/haxe/lib/polymod/git/polymod/hscript/_internal/PolymodInterpEx.hx:73: characters 14-43 : polymod.hscript._internal.ErrorEx should be hscript.Error
C:/Users/alexb/haxe/lib/polymod/git/polymod/hscript/_internal/PolymodInterpEx.hx:73: characters 14-43 : ... For function argument 'e'
C:/Users/alexb/haxe/lib/polymod/git/polymod/hscript/_internal/PolymodInterpEx.hx:450: characters 13-38 : polymod.hscript._internal.ErrorEx should be hscript.Error
C:/Users/alexb/haxe/lib/polymod/git/polymod/hscript/_internal/PolymodInterpEx.hx:450: characters 13-38 : ... For function argument 'e'
C:/Users/alexb/haxe/lib/polymod/git/polymod/hscript/_internal/PolymodInterpEx.hx:105: characters 13-40 : polymod.hscript._internal.ErrorEx should be hscript.Error
C:/Users/alexb/haxe/lib/polymod/git/polymod/hscript/_internal/PolymodInterpEx.hx:105: characters 13-40 : ... For function argument 'e'
C:/Users/alexb/haxe/lib/polymod/git/polymod/hscript/_internal/PolymodInterpEx.hx:483: characters 13-38 : polymod.hscript._internal.ErrorEx should be hscript.Error
C:/Users/alexb/haxe/lib/polymod/git/polymod/hscript/_internal/PolymodInterpEx.hx:483: characters 13-38 : ... For function argument 'e'
C:/Users/alexb/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:94: characters 7-25 : flixel.FlxType should be flixel.util.FlxAxes
C:/Users/alexb/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:142: characters 7-25 : flixel.FlxType should be flixel.util.FlxAxes
C:/Users/alexb/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:150: characters 18-19 : flixel.util.FlxAxes has no field x
C:/Users/alexb/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:151: characters 18-19 : flixel.util.FlxAxes has no field y
C:/Users/alexb/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:413: characters 7-25 : flixel.FlxType should be flixel.util.FlxAxes
C:/Users/alexb/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:419: characters 21-22 : flixel.util.FlxAxes has no field x
C:/Users/alexb/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:420: characters 21-22 : flixel.util.FlxAxes has no field y
C:/Users/alexb/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:423: characters 21-22 : flixel.util.FlxAxes has no field x
C:/Users/alexb/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:424: characters 21-22 : flixel.util.FlxAxes has no field y
C:/Users/alexb/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:426: characters 21-22 : flixel.util.FlxAxes has no field x
C:/Users/alexb/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:427: characters 21-22 : flixel.util.FlxAxes has no field y
C:/Users/alexb/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:429: characters 21-22 : flixel.util.FlxAxes has no field x
C:/Users/alexb/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:429: characters 44-45 : flixel.util.FlxAxes has no field x
C:/Users/alexb/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:430: characters 21-22 : flixel.util.FlxAxes has no field y
C:/Users/alexb/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:430: characters 44-45 : flixel.util.FlxAxes has no field y
C:/Users/alexb/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:450: characters 20-21 : flixel.util.FlxAxes has no field x
C:/Users/alexb/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:456: characters 20-21 : flixel.util.FlxAxes has no field y
C:/Users/alexb/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:493: characters 30-31 : flixel.util.FlxAxes has no field x
C:/Users/alexb/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:494: characters 30-31 : flixel.util.FlxAxes has no field y
C:/Users/alexb/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:191: characters 7-25 : flixel.FlxType should be flixel.util.FlxAxes
C:/Users/alexb/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:209: characters 7-25 : flixel.FlxType should be flixel.util.FlxAxes
C:/Users/alexb/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:212: characters 19-20 : flixel.util.FlxAxes has no field x
C:/Users/alexb/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:221: characters 19-20 : flixel.util.FlxAxes has no field y
C:/Users/alexb/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:262: characters 7-25 : flixel.FlxType should be flixel.util.FlxAxes
C:/Users/alexb/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:312: characters 7-25 : flixel.FlxType should be flixel.util.FlxAxes
C:/Users/alexb/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:316: characters 19-20 : flixel.util.FlxAxes has no field x
C:/Users/alexb/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:325: characters 19-20 : flixel.util.FlxAxes has no field y
C:/Users/alexb/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:182: characters 7-25 : flixel.FlxType should be flixel.util.FlxAxes
source/SelectLanguageState.hx:34: characters 70-71 : Int should be flixel.util.FlxAxes
source/SelectLanguageState.hx:34: characters 70-71 : ... For optional function argument 'repeatAxes'

im guessing im getting these errors bc i need a specific git, haxe and flixel version
heres the version in question: https://github.com/MoldyGH/VsDave/tree/80b2ae2044f923a64f39178fa70669554514a9e4

**Comment by MemeHoovy** [comment]
okay, there is so much you did wrong here, your just a lost cause

**Comment by alex-codes-stuff** [comment]
sadder

**Comment by mayo78** [comment]
you'll have to go to every single instance of a line that mentions newgrounds and comment it, idk why, but thats just what you gotta do. and also remove the line that mentions polymod in project.xml. (also for the errors about flxbackdrop unless you really want that you can just replace the flxbackdrops with like a blank flxsprite)

**Comment by benjaminpants** [comment]
We aren't providing support for older versions of Vs Dave.

**Comment by alex-codes-stuff** [comment]
kinda stoopid as i dont want support for this version but i mean srure

**Comment by MemeHoovy** [comment]
Ben said he wasn’t adding support for old versions
