### ISSUE TITLE
idk what to say

### ISSUE THREAD

**Issue by imdumlol** [MoldyGH/VsDave#64]
source/PlayState.hx:255: characters 12-24 : Type not found : VideoHandler
source/Character.hx:14: lines 14-770 : ... Defined in this class
source/Note.hx:166: characters 18-28 : Class has no field scrollType
source/CompatWarningState.hx:31: characters 114-116 : flixel.util.FlxAxes should be Float
source/CompatWarningState.hx:31: characters 114-116 : ... For optional function argument 'ScrollX'
source/SelectLanguageState.hx:35: characters 113-115 : flixel.util.FlxAxes should be Float
source/SelectLanguageState.hx:35: characters 113-115 : ... For optional function argument 'ScrollX'

this is also on dave engine

**Comment by Erizur** [comment]
1.- update hxcodec from the polybiusproxy repo
2.- we updated the repo for haxeflixel 5, so update flixel to the latest version.

**Comment by imdumlol** [comment]
Error: Failed with error: No such Project : haxeflixel

it can't find haxeflixel

**Comment by imdumlol** [comment]
never mind found it

**Comment by imdumlol** [comment]
now i just get this 

source/PlayState.hx:255: characters 12-24 : Type not found : VideoHandler
source/Character.hx:14: lines 14-770 : ... Defined in this class
source/Note.hx:166: characters 18-28 : Class<PlayState> has no field scrollType

**Comment by MemeHoovy** [comment]
> Error: Failed with error: No such Project : haxeflixel
> 
> it can't find haxeflixel

are you so dumb, that you can't find flixel, a fucking haxelib project that you can just easily find on the internet, just find that cunt, and the hxCodec project haxelib git hxCodec https://github.com/polybiusproxy/hxCodec use the fucking git version, and now stop making fucking issues about it

**Comment by imdumlol** [comment]
im still getting it

**Comment by imdumlol** [comment]
got it to work thx
